version: "3.8"

services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: jenkins-controller
    restart: unless-stopped
    ports:
      - "8080:8080"   # Web UI
      - "50000:50000" # JNLP agent port (Windows agent connects here)
    volumes:
      - jenkins_home:/var/jenkins_home
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=true
    user: root
    entrypoint: |
      sh -c '
      apt-get update && apt-get install -y maven git \
      && /usr/local/bin/jenkins.sh
      '

volumes:
  jenkins_home:
