node {
  stage("Checkout") {
    checkout scm
  }
  
  stage("Build") {
    dir('services\\grievance-service') {
      bat "mvn clean install -DskipTests"
    }
  }
  
  stage("Package & Move") {
    dir('services\\grievance-service') {
      def ts = bat(script: "@echo %date:~-10,2%%date:~-7,2%%date:~-4,4%%time:~0,2%%time:~3,2%%time:~6,2%", returnStdout: true).trim()
      def dest = "new_build_" + ts
      bat "if not exist " + dest + " mkdir " + dest
      bat "move target\\*-MVP.jar " + dest + "\\ || move target\\*.jar " + dest
      echo "Moved JAR to " + dest
    }
  }
  
  stage("Run") {
    dir('services\\grievance-service') {
      bat "start /B java -jar new_build_*\\*.jar"
      echo "Started jar"
    }
  }
}